sudo: required

language: generic

services:
  - docker

env:
  matrix:
    - VER=5.6
    - VER=7.0
    - VER=7.1
    - VER=7.2
    - VER=7.3
    - VER=7.4
  global:
    # DOCKER_USERNAME
    - secure: hJxx3pt08GGxbaSWKMYWXVvwlrn/sJbh4rpLveUGz5pd9C8IcvkOJsrXrtVqr7/4jb5/CQwz65cGyukxzbonvUZgt0mfmZ9GunpD1pz3IusjXvYlZOZ1LL/i6t57J7fMKtUXxBTWNQSS9pH7pEHixvMabS3kqQb74Nj6wQFNzucmnEQGCT0drs8NrlfEfaNdXkJ5ijqdY42QM0BfGU7SnO0/puaEapl3I/n1TLWf60YUV2etl8BaFZckX7ewHvLWs+nXtHUMSezO/9jupb2pOR600+/77Pdfj735hvymD/gAjzTMRJlcUAOThkQfwI4Zt4MoJKvjXbrcYYsz5yEk4o8wPRX/5lZUso2NNRR/J3ahTZZGpDxp+plwY+v6KYwC7L6Bc6HYZbDaxMMXvMokxjyyAtmewaWsVEf+VDTxg5wowJj6esfd+Z0a6IvBFiVxOzltRtR4SqLvFrjq5vPM+RHK1UStJOHCNjpDq5BrEo7bWp+Fi66LpWQYQEL15EjQy3xcx9pfY+5rHot0ClHSqror9RQmQSmmsQWZCFEcjwt07hbmwp75LjFeQm0wRAl6dBZ1CJly/6daVIv4cj7bh72McrhesXc2EmesxEbQaUd/rJjGhaoZ/joPR8gN2RLnCFPzCXdITHXWxThjUZZwPIqtJiI3xXR5vmWidV552ZA=
    # DOCKER_PASSWORD
    - secure: YfZCh36+apqqmIGrFx+VxhgUqNLNrAwp5BoYshJCHu0iZofVYPHxIsgauQ4vQZj/lYnqe0Ak7qG+s9vnt+OHb8rVyLaZXVRkKFFfbjuu3nOrdFgJwhFbWfjptWogoSM2X1wJtheO40oYAjegF7cq4Bxp14ux/telYCUm8mx7k/h1KoUJOzNzuZCyeh95bQPBAkzIKA1a9rupYMH/LOWLuoTCFmN0eU6VGjwK1XZoDq1uZpYk/YH8VAUvefSS2uE9/WLjoRSTJAk0A4tcVbzPN0FbDTGW59/MbqH6diZ8/KZjcALbmaNtGZGOixn0zgushSN9uSIJk9V/WKamTF08KCS79Ud1aIGYf5UtzBAycnPY2/Y7mA9Ktk/BTWui5OLk2XItY7Ts7N9ikFw+9i3e91YBxxGCVrnsLug+Ih1Ipjyu/8SN9Ttzqp2/6zBFf+sDFXTPnMpptSXTKMcXy/pJVVGIUe38L7BJdUKE1Xp4BqBVnJyaZL8UQVSKdh3kU6C/OfEud6HrIHfAKg6S71rOQBzOk+V+p/U5L4wQCJYLuyGFEuPdMP27wnLh3oUMhnkPK28EpuG0Z5RTH1Sd5MGaHThyDwEtJaECyIMndKY9Wx73gmvvwe2rrltkjHc44jyBG53B8iXNeG/kmKAqPewHHJbxC//A6ykFEnvO7tbF6To=

script:
  - make build-${VER}
  - make tag-${VER}
  - make test-${VER}

deploy:
  - provider: script
    script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && make deploy-${VER}
    on:
      branch: master

matrix:
  fast_finish: true
